@echo off
echo Starting validation...
pnpm install --frozen-lockfile
echo formatting...
pnpm format
echo format-check
pnpm format:check
echo linting...
pnpm lint
echo typchecking...
pnpm typecheck
echo testing...
pnpm test:coverage
echo building...
pnpm build
echo auditing...
pnpm audit --prod --audit-level=critical
echo Done.
